"""empty message

Revision ID: 17bc130e0307
Revises: 9e6bfb9a507d
Create Date: 2019-11-26 23:48:16.826248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bc130e0307'
down_revision = '9e6bfb9a507d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authenticators', ['credential_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authenticators', type_='unique')
    # ### end Alembic commands ###
