"""empty message

Revision ID: 9e6bfb9a507d
Revises: 7654b85e6b86
Create Date: 2019-11-22 01:01:46.780653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6bfb9a507d'
down_revision = '7654b85e6b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticators', sa.Column('credential_id', sa.String(), nullable=False))
    op.add_column('authenticators', sa.Column('public_key', sa.String(), nullable=False))
    op.add_column('authenticators', sa.Column('sign_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticators', 'sign_count')
    op.drop_column('authenticators', 'public_key')
    op.drop_column('authenticators', 'credential_id')
    # ### end Alembic commands ###
