"""empty message

Revision ID: a9ec729d07ea
Revises: 17bc130e0307
Create Date: 2019-11-27 00:17:39.858482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ec729d07ea'
down_revision = '17bc130e0307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticators', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('authenticators', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('authenticators', 'last_used_at')
    op.drop_column('authenticators', 'created_at')
    # ### end Alembic commands ###
