"""empty message

Revision ID: aa8d56230c6e
Revises: d58ca5e5b5ef
Create Date: 2019-11-27 00:26:08.669268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa8d56230c6e'
down_revision = 'd58ca5e5b5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authenticators', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('authenticators', sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('authenticators', 'last_used_at')
    op.drop_column('authenticators', 'created_at')
    # ### end Alembic commands ###
