"""empty message

Revision ID: d58ca5e5b5ef
Revises: a9ec729d07ea
Create Date: 2019-11-27 00:25:42.929012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd58ca5e5b5ef'
down_revision = 'a9ec729d07ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authenticators', 'created_at')
    op.drop_column('authenticators', 'last_used_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('authenticators', sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('authenticators', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
